description: >
  This job builds the application and persists to a workspace

docker:
  - image: circleci/php:7.4-browsers

steps:
  - checkout
  - install_nodejs
  - install_php_dependencies
  - remove_git_folders_from_php_dependencies
  - install_js_dependencies
  - run:
      name: Building customiser v2
      command: npm run cv2:install && npm run cv2:build
  - persist_to_workspace:
      root: .
      paths:
        - vendor
        - plugins
        - themes
        - client-mu-plugins
