description: >
  This job builds the application and persists to a workspace

docker:
  - image: circleci/php:7.4-browsers

parameters:
  first-npm-command:
    type: string
  second-npm-command:
    type: string

steps:
  - checkout
  - install_nodejs
  - install_php_dependencies
  - remove_git_folders_from_php_dependencies
  - run_npm_command_with_cache:
        command: << parameters.first-npm-command >>
  - run_npm_command_with_cache:
      command: << parameters.second-npm-command >>
  - persist_to_workspace:
      root: .
      paths:
        - vendor
        - plugins
        - themes
        - client-mu-plugins
